version: 2.1

jobs:
  build-and-test:
    resource_class: arm.medium
    docker:
      - image: docker:20.10.7-dind
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build and tag Docker runner image
          command: |
            docker build --target runner -t modbus_weather:runner .
      - run:
          name: Build and tag Docker builder image
          command: |
            docker build --target builder -t modbus_weather:builder .
      - run:
          name: Publish Docker image to DockerHub
          command: |
            docker tag modbus_weather:runner jaryh3/modbus_weather:latest
            echo "$DOCKERHUB_PASSWORD" | docker login -u jaryh3 --password-stdin
            docker push jaryh3/modbus_weather:latest

workflows:
  build-and-test:
    jobs:
      - build-and-test


