version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Build and tag Docker runner image
          command: |
            docker build --target runner -t weathermap:runner .
      - run:
          name: Build and tag Docker builder image
          command: |
            docker build --target builder -t weathermap:builder .
      - run:
          name: Publish Docker image to DockerHub
          command: |
            docker tag weathermap:latest jaryh3/weathermap:runner
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push jaryh3/weathermap:latest

workflows:
  build-and-test:
    jobs:
      - build-and-test


