version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202101-01
      cpu: arm
    steps:
      - checkout
      - run:
          name: Build and tag Docker runner image
          command: |
            docker build --target runner -t modbus_weather:runner .
      - run:
          name: Build and tag Docker builder image
          command: |
            docker build --target builder -t modbus_weather:builder .
      - run:
          name: Publish Docker image to DockerHub
          command: |
            docker tag modbus_weather:runner jaryh3/modbus_weather:latest
            echo "$DOCKERHUB_PASSWORD" | docker login -u jaryh3 --password-stdin
            docker push jaryh3/modbus_weather:latest

workflows:
  build-and-test:
    jobs:
      - build-and-test


